all:
  hosts:
    node1:
      ansible_host: 192.168.2.199
      ip: 192.168.2.199
      access_ip: 192.168.2.199
      ansible_ssh_user: root
    node2:
      ansible_host: 192.168.2.215
      ip: 192.168.2.215
      access_ip: 192.168.2.215
      ansible_ssh_user: root
    node3:
      ansible_host: 192.168.2.233
      ip: 192.168.2.233
      access_ip: 192.168.2.233
      ansible_ssh_user: root
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
