all:
  hosts:
    node1:
      ansible_host: 172.16.51.11
      ip: 172.16.51.11
      access_ip: 172.16.51.11
    node2:
      ansible_host: 172.16.51.12
      ip: 172.16.51.12
      access_ip: 172.16.51.12
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
